MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

EncryptionPrivateKey:
    settings-key: Bitcoin-SignService-EncryptionPrivateKey
NetworkType:
    settings-key: Bitcoin-Network